[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "PEnBQGAbFqZHnaWEaeu1Eu6MbbM5CNBw6oTWsSejAbB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/shooter/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
